apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgen-deployment
  labels:
    app: klos-demo
    component: loadgen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: klos-demo
      component: loadgen
  template:
    metadata:
      labels:
        app: klos-demo
        component: loadgen
    spec:
      containers:
        - name: loadgen
          image: ghcr.io/octopusdeploylabs/klos-demo:latest
          ports:
            - containerPort: 8080
              name: http
          command:
            - /loadgen
          env:
            - name: RPS
              value: "5"
          resources:
            limits:
              memory: 100Mi
              cpu: 500m