apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-cache
  labels:
    app: klos-demo
    component: messagecache
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: klos-demo
      component: messagecache
  template:
    metadata:
      labels:
        app: klos-demo
        component: messagecache
    spec:
      containers:
        - name: messagecache
          image: ghcr.io/octopusdeploylabs/klos-demo:v#{Octopus.Release.Number}
          ports:
            - containerPort: 8080
              name: http
          command:
            - /cache
          readinessProbe:
            httpGet:
              port: 8080
              path: /healthz
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          resources:
            requests:
              memory: 500Mi
              cpu: 100m
            limits:
              memory: 500Mi
              cpu: 100m