apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    app: klos-demo
    component: worker
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: klos-demo
      component: worker
  template:
    metadata:
      labels:
        app: klos-demo
        component: worker
    spec:
      containers:
        - name: worker
          image: ghcr.io/octopusdeploylabs/klos-demo:latest
          ports:
            - containerPort: 8080
              name: http
          command:
            - /worker
          env:
            - name: LetTheCeoDoThings
              value: #{LetTheCeoDoThings}
          readinessProbe:
            httpGet:
              port: 8080
              path: /healthz
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          resources:
            requests:
              memory: 100Mi
              cpu: 50m
            limits:
              memory: 100Mi
              cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: worker
spec:
  selector:
    app: klos-demo
    component: worker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
